services:
  redis:
    image: redis:7
    container_name: devkit-redis-v2
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:

